/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechniquesRouteImport } from './routes/techniques'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechniquesTechniqueIdRouteImport } from './routes/techniques.$techniqueId'

const TechniquesRoute = TechniquesRouteImport.update({
  id: '/techniques',
  path: '/techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniquesTechniqueIdRoute = TechniquesTechniqueIdRouteImport.update({
  id: '/$techniqueId',
  path: '/$techniqueId',
  getParentRoute: () => TechniquesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/techniques': typeof TechniquesRouteWithChildren
  '/techniques/$techniqueId': typeof TechniquesTechniqueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/techniques': typeof TechniquesRouteWithChildren
  '/techniques/$techniqueId': typeof TechniquesTechniqueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/techniques': typeof TechniquesRouteWithChildren
  '/techniques/$techniqueId': typeof TechniquesTechniqueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/approvals' | '/techniques' | '/techniques/$techniqueId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/approvals' | '/techniques' | '/techniques/$techniqueId'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/techniques'
    | '/techniques/$techniqueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  TechniquesRoute: typeof TechniquesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/techniques': {
      id: '/techniques'
      path: '/techniques'
      fullPath: '/techniques'
      preLoaderRoute: typeof TechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techniques/$techniqueId': {
      id: '/techniques/$techniqueId'
      path: '/$techniqueId'
      fullPath: '/techniques/$techniqueId'
      preLoaderRoute: typeof TechniquesTechniqueIdRouteImport
      parentRoute: typeof TechniquesRoute
    }
  }
}

interface TechniquesRouteChildren {
  TechniquesTechniqueIdRoute: typeof TechniquesTechniqueIdRoute
}

const TechniquesRouteChildren: TechniquesRouteChildren = {
  TechniquesTechniqueIdRoute: TechniquesTechniqueIdRoute,
}

const TechniquesRouteWithChildren = TechniquesRoute._addFileChildren(
  TechniquesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  TechniquesRoute: TechniquesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
